// Code generated by MockGen. DO NOT EDIT.
// Source: credential_store.go

// Package credential_store is a generated GoMock package.
package credential_store

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCredStorage is a mock of CredStorage interface.
type MockCredStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCredStorageMockRecorder
}

// MockCredStorageMockRecorder is the mock recorder for MockCredStorage.
type MockCredStorageMockRecorder struct {
	mock *MockCredStorage
}

// NewMockCredStorage creates a new mock instance.
func NewMockCredStorage(ctrl *gomock.Controller) *MockCredStorage {
	mock := &MockCredStorage{ctrl: ctrl}
	mock.recorder = &MockCredStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredStorage) EXPECT() *MockCredStorageMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCredStorage) Create() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCredStorageMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCredStorage)(nil).Create))
}

// Delete mocks base method.
func (m *MockCredStorage) Delete() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete")
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCredStorageMockRecorder) Delete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCredStorage)(nil).Delete))
}

// Find mocks base method.
func (m *MockCredStorage) Find() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find")
	ret0, _ := ret[0].(error)
	return ret0
}

// Find indicates an expected call of Find.
func (mr *MockCredStorageMockRecorder) Find() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCredStorage)(nil).Find))
}

// Update mocks base method.
func (m *MockCredStorage) Update() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update")
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCredStorageMockRecorder) Update() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCredStorage)(nil).Update))
}
